version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
  logstash:
    image: docker.elastic.co/logstash/logstash:7.15.0
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - 5001:5000
      - 9600:9600
  kibana:
    image: docker.elastic.co/kibana/kibana:8.1.2
    ports:
      - 5601:5601
